[package]
name = "web_server"
version = "0.1.0"
authors = ["rafaeldias <rafael.dias@bemobi.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"